const app=document.getElementById("app");
function norm(v,mode){let s=String(v||"").trim();return mode==="code"?s.replace(/\s/g,"").replace(/;$/,""):s}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function card(l){const ready=!!l.tasks;const done=ready?l.tasks.filter(t=>Progress.isDone(t.id)).length:0;return ready?'<a class="card topic-card" href="#/lesson/'+l.id+'"><div class="topic-icon">'+l.icon+'</div><h3>'+l.title+'</h3><p class="muted">'+l.short+'</p><span class="badge">'+done+'/'+l.tasks.length+' заданий</span></a>':'<div class="card topic-card"><div class="topic-icon">'+l.icon+'</div><h3>'+l.title+'</h3><p class="muted">'+l.short+'</p><span class="badge">Скоро</span></div>'}
function home(){const p=Progress.percent();app.innerHTML='<section class="hero"><h1>🐍 Python с нуля</h1><p>Игровой курс программирования для школьников 10–14 лет. Изучай Python небольшими шагами, решай задания и собирай свой прогресс!</p><a class="btn btn-light" href="#/lesson/variables">🚀 Начать обучение</a></section><section class="card"><h2>🏆 Твой прогресс</h2><div class="progress-wrap"><div class="progress-bar" style="width:'+p+'%"></div></div><p><strong>'+p+'%</strong> — выполнено заданий: '+Progress.doneTasks()+' из '+Progress.totalTasks()+'</p></section><h2 class="section-title">📚 Темы курса</h2><div class="grid">'+LESSONS.map(card).join("")+'</div>'}
function topics(){app.innerHTML='<div class="lesson-header"><div class="breadcrumb">Главная → Темы</div><h1>📚 Темы курса</h1><p class="muted">Проходим Python от простого к сложному.</p></div><div class="grid">'+LESSONS.map(card).join("")+'</div>'}
function progress(){const p=Progress.percent();app.innerHTML='<div class="lesson-header"><div class="breadcrumb">Главная → Прогресс</div><h1>🏆 Мой прогресс</h1></div><section class="card"><h2>'+(p===100?"🎉 Курс выполнен!":"Так держать!")+'</h2><div class="progress-wrap"><div class="progress-bar" style="width:'+p+'%"></div></div><p><strong>'+p+'%</strong> курса • '+Progress.doneTasks()+' из '+Progress.totalTasks()+' заданий</p></section>'}
function task(t){const labels={easy:"🟢 Легко",medium:"🟡 Средне",hard:"🔴 Сложно"};let input=t.type==="choice"?t.options.map(o=>'<label><input type="radio" name="'+t.id+'" value="'+esc(o)+'"> '+esc(o)+'</label><br>').join(""):'<textarea id="input-'+t.id+'" placeholder="Напиши свой ответ здесь..."></textarea>';return '<article class="card task '+t.level+'"><span class="badge">'+labels[t.level]+'</span><h3>'+t.title+(Progress.isDone(t.id)?" ✅":"")+'</h3><p>'+t.question+'</p>'+input+'<button class="btn check-btn" data-id="'+t.id+'">'+(Progress.isDone(t.id)?"Выполнено ✓":"Проверить")+'</button><div class="feedback" id="feedback-'+t.id+'">'+(Progress.isDone(t.id)?'<span class="success">🎉 Задание уже выполнено!</span>':"")+'</div></article>'}
function lesson(id){const l=LESSONS.find(x=>x.id===id);if(!l||!l.tasks)return home();app.innerHTML='<div class="lesson-header"><div class="breadcrumb"><a href="#/">Главная</a> → '+l.title+'</div><h1>'+l.icon+' '+l.title+'</h1><p class="muted">'+l.description+'</p></div><section class="card lesson-section"><h2>📖 Теория</h2>'+l.theory.map(x=>'<p>'+x+'</p>').join("")+'</section><section class="lesson-section"><h2>💡 Разберём пример</h2>'+l.examples.map(x=>'<div class="card lesson-section"><pre class="code"><code>'+esc(x.code)+'</code></pre><p class="muted">💡 '+x.note+'</p></div>').join("")+'</section><section class="lesson-section"><h2>🎬 Видеоурок</h2><div class="video-placeholder"><div><strong>▶</strong>Здесь появится видеоурок.<br>Ссылку добавим позже.</div></div></section><section class="lesson-section"><h2>🧩 Практика</h2><p class="muted">Выполняй задания по порядку. Ошибки помогают учиться!</p>'+l.tasks.map(task).join("")+'</section><a class="back" href="#/topics">← Все темы</a>';bind()}
function bind(){document.querySelectorAll(".check-btn").forEach(b=>b.onclick=()=>{const t=LESSONS.flatMap(l=>l.tasks||[]).find(x=>x.id===b.dataset.id);let v="";if(t.type==="choice"){const s=document.querySelector('input[name="'+t.id+'"]:checked');v=s?s.value:""}else v=document.getElementById("input-"+t.id).value;const f=document.getElementById("feedback-"+t.id);if(norm(v,t.normalize)===norm(t.answer,t.normalize)){Progress.complete(t.id);f.innerHTML='<span class="success">🎉 Отлично! Задание выполнено!</span>';b.textContent="Выполнено ✓";b.disabled=true}else f.innerHTML='<span class="error">💡 Пока не получилось. Проверь ответ и попробуй ещё раз!</span>'})}
function route(){const h=location.hash||"#/";if(h==="#/"||h==="#")home();else if(h==="#/topics")topics();else if(h==="#/progress")progress();else if(h.startsWith("#/lesson/"))lesson(h.split("/")[2]);else home();window.scrollTo({top:0,behavior:"smooth"})}
addEventListener("hashchange",route);route();