window.LESSONS=[
{id:"intro",icon:"⚪",title:"Знакомство с Python",short:"Что такое программа и как мыслить как программист.",description:"Первая встреча с Python, командами и ошибками.",
theory:["Программа — это последовательность команд, которую компьютер выполняет по правилам.","Python — язык программирования с понятным синтаксисом. Мы будем учиться записывать команды, читать результат и исправлять ошибки.","В программировании важно не угадывать ответ, а разбивать большую задачу на маленькие шаги. Если программа не работает, ошибка — это подсказка для поиска проблемы."],
examples:[{code:"print("+""Привет, Python!""+")",note:"Команда print() показывает сообщение на экране."},{code:"print(2 + 3)",note:"Python может не только выводить текст, но и считать."}],
tasks:[
{id:"i1",level:"easy",title:"Что такое программа",question:"Что выполняет компьютер?",type:"choice",options:["Последовательность команд","Только картинки","Только игры"],answer:"Последовательность команд"},
{id:"i2",level:"easy",title:"Python",question:"Python — это...",type:"choice",options:["язык программирования","браузер","операционная система"],answer:"язык программирования"},
{id:"i3",level:"easy",title:"Первая команда",question:"Какая команда выводит текст?",type:"choice",options:["print()","input()","if"],answer:"print()"},
{id:"i4",level:"easy",title:"Результат",question:"Что выведет print(2 + 3)?",type:"choice",options:["5","23","2 + 3"],answer:"5"},
{id:"i5",level:"medium",title:"Привет",question:"Напиши команду, выводящую Привет!",type:"text",answer:"print("Привет!")",normalize:"code"},
{id:"i6",level:"medium",title:"Считаем",question:"Напиши код, который выводит 10 + 5.",type:"text",answer:"print(10+5)",normalize:"code"},
{id:"i7",level:"medium",title:"Две команды",question:"Выведи сначала Hello, затем Python двумя командами.",type:"text",answer:"print("Hello")\nprint("Python")",normalize:"code"},
{id:"i8",level:"hard",title:"Три шага",question:"Выведи числа 1, 2 и 3 тремя командами print().",type:"text",answer:"print(1)\nprint(2)\nprint(3)",normalize:"code"},
{id:"i9",level:"hard",title:"Математик",question:"Выведи результат 7 * 8.",type:"text",answer:"print(7*8)",normalize:"code"},
{id:"i10",level:"hard",title:"Мини-программа",question:"Выведи строками имя Python и результат 20 + 22.",type:"text",answer:"print("Python")\nprint(20+22)",normalize:"code"}]},
{id:"io",icon:"🟣",title:"Ввод и вывод",short:"Общаемся с программой через print() и input().",description:"Получаем данные от пользователя и показываем результат.",
theory:["print() выводит информацию на экран, а input() останавливает программу и ждёт текст от пользователя.","Результат input() — строка. Если нам нужно число, позже мы научимся превращать строку в int() или float().","Комбинация input() и print() превращает программу из набора команд в маленький диалог с пользователем."],
examples:[{code:"name = input("Как тебя зовут? ")\nprint("Привет, " + name)",note:"Программа получает имя и использует его в ответе."},{code:"age = input("Сколько тебе лет? ")\nprint(age)",note:"Введённый ответ можно сохранить в переменную."}],
tasks:[
{id:"io1",level:"easy",title:"Вывод",question:"Что выводит информацию?",type:"choice",options:["print()","input()","range()"],answer:"print()"},
{id:"io2",level:"easy",title:"Ввод",question:"Какая команда получает ввод пользователя?",type:"choice",options:["input()","print()","type()"],answer:"input()"},
{id:"io3",level:"easy",title:"Результат input",question:"Какой тип возвращает обычный input()?",type:"choice",options:["строку","число","список"],answer:"строку"},
{id:"io4",level:"medium",title:"Имя",question:"Сохрани ответ пользователя в переменную name.",type:"text",answer:"name=input()",normalize:"code"},
{id:"io5",level:"medium",title:"Вопрос",question:"Напиши input() с вопросом \"Как тебя зовут? \" и сохрани ответ в name.",type:"text",answer:"name=input("Как тебя зовут? ")",normalize:"code"},
{id:"io6",level:"medium",title:"Ответ",question:"Выведи переменную name через print().",type:"text",answer:"print(name)",normalize:"code"},
{id:"io7",level:"medium",title:"Диалог",question:"Получи name и выведи \"Привет, \" + name.",type:"text",answer:"name=input()\nprint("Привет, "+name)",normalize:"code"},
{id:"io8",level:"hard",title:"Любимый цвет",question:"Получи color и выведи \"Твой цвет: \" + color.",type:"text",answer:"color=input()\nprint("Твой цвет: "+color)",normalize:"code"},
{id:"io9",level:"hard",title:"Два ответа",question:"Получи name и city, затем выведи name и city двумя print().",type:"text",answer:"name=input()\ncity=input()\nprint(name)\nprint(city)",normalize:"code"},
{id:"io10",level:"hard",title:"Мини-анкета",question:"Получи name и hobby, затем выведи \"Имя: \" + name и \"Хобби: \" + hobby.",type:"text",answer:"name=input()\nhobby=input()\nprint("Имя: "+name)\nprint("Хобби: "+hobby)",normalize:"code"}]},
{id:"variables",icon:"🟢",title:"Переменные",short:"Учимся хранить информацию в программе.",description:"Имена, значения и присваивание.",
theory:["Переменная — это имя, под которым программа хранит значение.","В Python используется присваивание: age = 12. Сначала пишем имя, затем =, затем значение.","Переменную можно использовать много раз и менять её значение. Хорошие имена помогают понимать программу."],
examples:[{code:"name = "Маша"\nage = 12\nprint(name)\nprint(age)",note:"В name и age хранятся разные значения."},{code:"score = 10\nscore = 15\nprint(score)",note:"После второго присваивания score хранит 15."}],
tasks:[
{id:"v1",level:"easy",title:"Найди переменную",question:"Какая переменная хранит возраст?",type:"choice",options:["name","age","print"],answer:"age"},
{id:"v2",level:"easy",title:"Имя переменной",question:"Как называется переменная в name = \"Аня\"?",type:"choice",options:["name","Аня","="],answer:"name"},
{id:"v3",level:"easy",title:"Значение",question:"Что хранится в score после score = 10?",type:"choice",options:["score","10","print"],answer:"10"},
{id:"v4",level:"medium",title:"Создай age",question:"Создай age со значением 12.",type:"text",answer:"age=12",normalize:"code"},
{id:"v5",level:"medium",title:"Создай имя",question:"Создай name со строкой \"Ира\".",type:"text",answer:"name=\"Ира\"",normalize:"code"},
{id:"v6",level:"medium",title:"Измени значение",question:"Создай score = 5, затем измени его на 10.",type:"text",answer:"score=5\nscore=10",normalize:"code"},
{id:"v7",level:"medium",title:"Выведи переменную",question:"Создай city = \"Алматы\" и выведи city.",type:"text",answer:"city=\"Алматы\"\nprint(city)",normalize:"code"},
{id:"v8",level:"hard",title:"Возраст через год",question:"Создай age = 12 и next_age = 13.",type:"text",answer:"age=12\nnext_age=13",normalize:"code"},
{id:"v9",level:"hard",title:"Карточка ученика",question:"Создай name = \"Саша\", age = 11 и выведи name.",type:"text",answer:"name=\"Саша\"\nage=11\nprint(name)",normalize:"code"},
{id:"v10",level:"hard",title:"Мини-профиль",question:"Создай name = \"Олег\", age = 14, city = \"Темиртау\" и выведи age.",type:"text",answer:"name=\"Олег\"\nage=14\ncity=\"Темиртау\"\nprint(age)",normalize:"code"}]},
{id:"types",icon:"🔵",title:"Типы данных",short:"Числа, строки и логические значения.",description:"Учимся выбирать подходящий тип данных.",
theory:["Данные бывают разных типов. int хранит целые числа, float — дробные, str — текст, bool — True или False.","Строки заключают в кавычки: "Python". Числа пишут без кавычек: 14.","Функция type() помогает проверить тип значения. Понимание типов важно, потому что разные данные можно обрабатывать по-разному."],
examples:[{code:"age = 12\nname = "Маша"\nheight = 1.55\nready = True",note:"Здесь используются int, str, float и bool."},{code:"print(type(12))\nprint(type("Python"))",note:"type() показывает тип значения."}],
tasks:[
{id:"t1",level:"easy",title:"Целое число",question:"Какой тип у 25?",type:"choice",options:["int","str","bool"],answer:"int"},
{id:"t2",level:"easy",title:"Строка",question:"Какой тип у \"Привет\"?",type:"choice",options:["int","str","float"],answer:"str"},
{id:"t3",level:"easy",title:"Логика",question:"Что является bool?",type:"choice",options:["True","12","\"да\""],answer:"True"},
{id:"t4",level:"medium",title:"Создай число",question:"Создай age = 13.",type:"text",answer:"age=13",normalize:"code"},
{id:"t5",level:"medium",title:"Создай строку",question:"Создай name = \"Аня\".",type:"text",answer:"name=\"Аня\"",normalize:"code"},
{id:"t6",level:"medium",title:"Дробное число",question:"Создай height = 1.6.",type:"text",answer:"height=1.6",normalize:"code"},
{id:"t7",level:"medium",title:"Проверка типа",question:"Выведи тип age.",type:"text",answer:"print(type(age))",normalize:"code"},
{id:"t8",level:"hard",title:"Три типа",question:"Создай age = 12, name = \"Лена\", ready = True.",type:"text",answer:"age=12\nname=\"Лена\"\nready=True",normalize:"code"},
{id:"t9",level:"hard",title:"Определи типы",question:"Выведи типы 10, \"Python\" и 2.5.",type:"text",answer:"print(type(10))\nprint(type(\"Python\"))\nprint(type(2.5))",normalize:"code"},
{id:"t10",level:"hard",title:"Анкета",question:"Создай name = \"Иван\", age = 14, student = True и выведи type(age).",type:"text",answer:"name=\"Иван\"\nage=14\nstudent=True\nprint(type(age))",normalize:"code"}]},
{id:"operators",icon:"🧮",title:"Арифметика и операторы",short:"Считаем и сравниваем значения.",description:"Математические операции и порядок действий.",
theory:["Основные арифметические операторы: + сложение, - вычитание, * умножение, / деление.","Оператор % находит остаток от деления, а ** возводит число в степень.","Сначала выполняются скобки, затем степень, затем умножение и деление, затем сложение и вычитание. Скобки помогают явно показать порядок."],
examples:[{code:"a = 10\nb = 3\nprint(a + b)\nprint(a % b)",note:"Получаем сумму и остаток от деления."},{code:"print(2 + 3 * 4)\nprint((2 + 3) * 4)",note:"Скобки меняют порядок вычислений."}],
tasks:[
{id:"a1",level:"easy",title:"Сложение",question:"Чему равно 7 + 5?",type:"choice",options:["10","12","13"],answer:"12"},
{id:"a2",level:"easy",title:"Умножение",question:"Чему равно 4 * 3?",type:"choice",options:["7","12","14"],answer:"12"},
{id:"a3",level:"easy",title:"Остаток",question:"Чему равно 10 % 3?",type:"choice",options:["0","1","3"],answer:"1"},
{id:"a4",level:"medium",title:"Сумма",question:"Создай a = 7, b = 5 и выведи сумму.",type:"text",answer:"a=7\nb=5\nprint(a+b)",normalize:"code"},
{id:"a5",level:"medium",title:"Разность",question:"Создай a = 10, b = 4 и выведи a - b.",type:"text",answer:"a=10\nb=4\nprint(a-b)",normalize:"code"},
{id:"a6",level:"medium",title:"Произведение",question:"Создай x = 6, y = 3 и выведи x * y.",type:"text",answer:"x=6\ny=3\nprint(x*y)",normalize:"code"},
{id:"a7",level:"medium",title:"Степень",question:"Выведи 2 в третьей степени через **.",type:"text",answer:"print(2**3)",normalize:"code"},
{id:"a8",level:"hard",title:"Периметр",question:"Создай a = 5, b = 3 и выведи 2*(a+b).",type:"text",answer:"a=5\nb=3\nprint(2*(a+b))",normalize:"code"},
{id:"a9",level:"hard",title:"Среднее",question:"Создай a = 10, b = 20 и выведи их среднее арифметическое.",type:"text",answer:"a=10\nb=20\nprint((a+b)/2)",normalize:"code"},
{id:"a10",level:"hard",title:"Выражение",question:"Выведи результат (8 + 4) * 2 - 5.",type:"text",answer:"print((8+4)*2-5)",normalize:"code"}]},
{id:"linear",icon:"🟡",title:"Линейные алгоритмы",short:"Строим программы шаг за шагом.",description:"Команды выполняются последовательно.",
theory:["Линейный алгоритм — это последовательность действий без выбора и повторения: команда 1, затем команда 2, затем команда 3.","Такие алгоритмы встречаются повсюду: расчёт покупки, перевод единиц, вычисление площади.","Полезный навык — сначала записать алгоритм словами, а потом перевести каждый шаг в Python."],
examples:[{code:"a = 5\nb = 3\ns = a * b\nprint(s)",note:"Четыре последовательных шага вычисляют площадь."},{code:"price = 100\ncount = 3\ntotal = price * count\nprint(total)",note:"Программа считает стоимость нескольких товаров."}],
tasks:[
{id:"l1",level:"easy",title:"Площадь",question:"Площадь прямоугольника 5 × 3 равна?",type:"choice",options:["8","15","16"],answer:"15"},
{id:"l2",level:"easy",title:"Цена",question:"3 товара по 20 стоят?",type:"choice",options:["40","60","80"],answer:"60"},
{id:"l3",level:"easy",title:"Порядок",question:"Что в линейном алгоритме происходит первым?",type:"choice",options:["Первая команда","Последняя команда","Случайная команда"],answer:"Первая команда"},
{id:"l4",level:"medium",title:"Сумма",question:"Создай a = 7, b = 5 и выведи сумму.",type:"text",answer:"a=7\nb=5\nprint(a+b)",normalize:"code"},
{id:"l5",level:"medium",title:"Разность",question:"Создай a = 10, b = 4 и выведи a - b.",type:"text",answer:"a=10\nb=4\nprint(a-b)",normalize:"code"},
{id:"l6",level:"medium",title:"Покупка",question:"price = 30, count = 4. Выведи стоимость.",type:"text",answer:"price=30\ncount=4\nprint(price*count)",normalize:"code"},
{id:"l7",level:"medium",title:"Площадь",question:"Создай width = 6, height = 4 и выведи площадь.",type:"text",answer:"width=6\nheight=4\nprint(width*height)",normalize:"code"},
{id:"l8",level:"hard",title:"Периметр",question:"Создай a = 5, b = 3 и выведи периметр.",type:"text",answer:"a=5\nb=3\nprint(2*(a+b))",normalize:"code"},
{id:"l9",level:"hard",title:"Скорость",question:"Создай distance = 100, time = 2 и выведи distance/time.",type:"text",answer:"distance=100\ntime=2\nprint(distance/time)",normalize:"code"},
{id:"l10",level:"hard",title:"Чек",question:"Создай price = 25, count = 4, discount = 10 и выведи price*count-discount.",type:"text",answer:"price=25\ncount=4\ndiscount=10\nprint(price*count-discount)",normalize:"code"}]},
{id:"conditions",icon:"🟠",title:"Условные алгоритмы",short:"Учимся принимать решения.",description:"if, elif, else и сравнения.",
theory:["Условие позволяет программе выбрать действие. Сначала проверяется выражение после if.","Операторы сравнения: == равно, != не равно, > больше, < меньше, >= больше или равно, <= меньше или равно.","elif добавляет дополнительные варианты, а else срабатывает, если предыдущие условия не подошли."],
examples:[{code:"age = 12\nif age >= 12:\n    print("Можно!")",note:"Отступ показывает, какие команды относятся к if."},{code:"score = 5\nif score >= 5:\n    print("Ура!")\nelse:\n    print("Попробуй ещё")",note:"Программа выбирает один из двух вариантов."}],
tasks:[
{id:"c1",level:"easy",title:"Равно",question:"Как записать «x равно 10»?",type:"choice",options:["x = 10","x == 10","x != 10"],answer:"x == 10"},
{id:"c2",level:"easy",title:"Если",question:"Какое слово начинает условие?",type:"choice",options:["if","for","def"],answer:"if"},
{id:"c3",level:"easy",title:"Иначе",question:"Какое слово задаёт другой вариант?",type:"choice",options:["else","print","input"],answer:"else"},
{id:"c4",level:"medium",title:"Возраст",question:"Выведи \"Можно\", если age >= 12.",type:"text",answer:"if age>=12:\n    print(\"Можно\")",normalize:"code"},
{id:"c5",level:"medium",title:"Два варианта",question:"Если score >= 5 — \"Ура\", иначе — \"Ещё раз\".",type:"text",answer:"if score>=5:\n    print(\"Ура\")\nelse:\n    print(\"Ещё раз\")",normalize:"code"},
{id:"c6",level:"medium",title:"Равно",question:"Выведи \"Да\", если x == 10.",type:"text",answer:"if x==10:\n    print(\"Да\")",normalize:"code"},
{id:"c7",level:"medium",title:"Больше",question:"Выведи \"Большое\", если number > 100.",type:"text",answer:"if number>100:\n    print(\"Большое\")",normalize:"code"},
{id:"c8",level:"hard",title:"Чётность",question:"Выведи \"Чётное\", если number % 2 == 0, иначе \"Нечётное\".",type:"text",answer:"if number%2==0:\n    print(\"Чётное\")\nelse:\n    print(\"Нечётное\")",normalize:"code"},
{id:"c9",level:"hard",title:"Оценка",question:"Если score >= 5 — \"Молодец\", иначе — \"Попробуй ещё\".",type:"text",answer:"if score>=5:\n    print(\"Молодец\")\nelse:\n    print(\"Попробуй ещё\")",normalize:"code"},
{id:"c10",level:"hard",title:"Три варианта",question:"Для age: <7 — \"Малыш\", <14 — \"Школьник\", иначе — \"Подросток\".",type:"text",answer:"if age<7:\n    print(\"Малыш\")\nelif age<14:\n    print(\"Школьник\")\nelse:\n    print(\"Подросток\")",normalize:"code"}]},
{id:"loops",icon:"🔴",title:"Циклы",short:"Повторяем действия без копирования кода.",description:"for, while и range().",
theory:["Цикл нужен, когда действие надо повторить. Вместо пяти одинаковых print() можно использовать один цикл.","for часто используется с range(), когда известно количество повторений. range(5) даёт числа 0, 1, 2, 3, 4.","while повторяет блок, пока условие истинно. В таком цикле важно изменять данные, чтобы условие когда-нибудь стало ложным."],
examples:[{code:"for i in range(5):\n    print(i)",note:"Цикл выводит 0–4."},{code:"count = 3\nwhile count > 0:\n    print(count)\n    count = count - 1",note:"Счётчик уменьшается, поэтому цикл заканчивается."}],
tasks:[
{id:"o1",level:"easy",title:"for",question:"Какое слово используется для цикла по последовательности?",type:"choice",options:["for","if","def"],answer:"for"},
{id:"o2",level:"easy",title:"range(3)",question:"Какие числа даёт range(3)?",type:"choice",options:["0, 1, 2","1, 2, 3","0, 1, 2, 3"],answer:"0, 1, 2"},
{id:"o3",level:"easy",title:"while",question:"Какой цикл работает пока условие истинно?",type:"choice",options:["while","for","else"],answer:"while"},
{id:"o4",level:"medium",title:"Пять раз",question:"Выведи \"Привет\" 5 раз.",type:"text",answer:"for i in range(5):\n    print(\"Привет\")",normalize:"code"},
{id:"o5",level:"medium",title:"Числа",question:"Выведи числа 0–4.",type:"text",answer:"for i in range(5):\n    print(i)",normalize:"code"},
{id:"o6",level:"medium",title:"От 1 до 5",question:"Выведи числа 1–5.",type:"text",answer:"for i in range(1,6):\n    print(i)",normalize:"code"},
{id:"o7",level:"medium",title:"Обратный отсчёт",question:"count = 3; while выводит count и уменьшает его на 1.",type:"text",answer:"count=3\nwhile count>0:\n    print(count)\n    count=count-1",normalize:"code"},
{id:"o8",level:"hard",title:"Квадраты",question:"Выведи квадраты чисел 1, 2 и 3.",type:"text",answer:"for i in range(1,4):\n    print(i*i)",normalize:"code"},
{id:"o9",level:"hard",title:"Сумма",question:"Создай total = 0 и сложи в цикле числа 1–5, затем выведи total.",type:"text",answer:"total=0\nfor i in range(1,6):\n    total=total+i\nprint(total)",normalize:"code"},
{id:"o10",level:"hard",title:"Финальный цикл",question:"Выведи \"Python с нуля!\" 3 раза через for.",type:"text",answer:"for i in range(3):\n    print(\"Python с нуля!\")",normalize:"code"}]},
{id:"strings",icon:"📝",title:"Строки",short:"Работаем с текстом и строковыми методами.",description:"Склеивание, длина строки и полезные методы.",
theory:["Строка (str) — последовательность символов. Её можно соединять оператором +.","Функция len() возвращает количество символов. У строк есть методы, например upper(), lower() и replace().","Строки позволяют создавать приветствия, сообщения, имена и другой текст, который вводит пользователь."],
examples:[{code:"name = "Маша"\nprint("Привет, " + name)",note:"Оператор + соединяет строки."},{code:"text = "Python"\nprint(len(text))\nprint(text.upper())",note:"len() считает символы, upper() делает буквы заглавными."}],
tasks:[
{id:"s1",level:"easy",title:"Строка",question:"Что является строкой?",type:"choice",options:["\"Python\"","123","True"],answer:"\"Python\""},
{id:"s2",level:"easy",title:"Длина",question:"Чему равен len(\"cat\")?",type:"choice",options:["2","3","4"],answer:"3"},
{id:"s3",level:"easy",title:"Заглавные",question:"Какой метод делает строку заглавными?",type:"choice",options:["upper()","lower()","count()"],answer:"upper()"},
{id:"s4",level:"medium",title:"Склейка",question:"Создай name = \"Маша\" и выведи \"Привет, \" + name.",type:"text",answer:"name=\"Маша\"\nprint(\"Привет, \"+name)",normalize:"code"},
{id:"s5",level:"medium",title:"Длина",question:"Выведи длину строки \"Python\".",type:"text",answer:"print(len(\"Python\"))",normalize:"code"},
{id:"s6",level:"medium",title:"Верхний регистр",question:"Выведи \"hello\" в верхнем регистре.",type:"text",answer:"print(\"hello\".upper())",normalize:"code"},
{id:"s7",level:"medium",title:"Нижний регистр",question:"Выведи \"PYTHON\" в нижнем регистре.",type:"text",answer:"print(\"PYTHON\".lower())",normalize:"code"},
{id:"s8",level:"hard",title:"Замена",question:"Замени в \"Я люблю Java\" слово Java на Python.",type:"text",answer:"print(\"Я люблю Java\".replace(\"Java\",\"Python\"))",normalize:"code"},
{id:"s9",level:"hard",title:"Приветствие",question:"Получи name через input() и выведи \"Привет, \" + name + \"!\".",type:"text",answer:"name=input()\nprint(\"Привет, "+name+\"!\")",normalize:"code"},
{id:"s10",level:"hard",title:"Мини-редактор",question:"Создай text = \"python\", затем выведи его длину и верхний регистр.",type:"text",answer:"text=\"python\"\nprint(len(text))\nprint(text.upper())",normalize:"code"}]},
{id:"lists",icon:"🧰",title:"Списки",short:"Храним много значений в одной переменной.",description:"Создание, индексы и простые операции со списками.",
theory:["Список хранит несколько значений: fruits = ["яблоко", "банан"].","Индексация начинается с нуля: fruits[0] — первый элемент. Можно менять элементы и добавлять новые с помощью append().","Списки полезны, когда данных много: оценки, имена друзей, товары или результаты игры."],
examples:[{code:"fruits = ["яблоко", "банан", "груша"]\nprint(fruits[0])",note:"Первый элемент имеет индекс 0."},{code:"scores = [5, 4]\nscores.append(5)\nprint(scores)",note:"append() добавляет элемент в конец списка."}],
tasks:[
{id:"p1",level:"easy",title:"Список",question:"Как выглядит список из 1, 2 и 3?",type:"choice",options:["[1, 2, 3]","(1, 2, 3)","{1, 2, 3}"],answer:"[1, 2, 3]"},
{id:"p2",level:"easy",title:"Первый элемент",question:"Как получить первый элемент a = [10, 20, 30]?",type:"choice",options:["a[0]","a[1]","a[3]"],answer:"a[0]"},
{id:"p3",level:"easy",title:"Добавление",question:"Как добавить элемент в конец списка?",type:"choice",options:["append()","add()","push()"],answer:"append()"},
{id:"p4",level:"medium",title:"Создай список",question:"Создай numbers со списком 1, 2, 3.",type:"text",answer:"numbers=[1,2,3]",normalize:"code"},
{id:"p5",level:"medium",title:"Первый",question:"Создай fruits = [\"яблоко\", \"банан\"] и выведи первый элемент.",type:"text",answer:"fruits=[\"яблоко\",\"банан\"]\nprint(fruits[0])",normalize:"code"},
{id:"p6",level:"medium",title:"Добавь",question:"Создай scores = [5, 4] и добавь 5.",type:"text",answer:"scores=[5,4]\nscores.append(5)",normalize:"code"},
{id:"p7",level:"medium",title:"Длина списка",question:"Создай a = [1,2,3,4] и выведи len(a).",type:"text",answer:"a=[1,2,3,4]\nprint(len(a))",normalize:"code"},
{id:"p8",level:"hard",title:"Последний",question:"Создай a = [10,20,30] и выведи последний элемент через индекс -1.",type:"text",answer:"a=[10,20,30]\nprint(a[-1])",normalize:"code"},
{id:"p9",level:"hard",title:"Список имён",question:"Создай names из трёх имён и выведи второе.",type:"text",answer:"names=[\"Аня\",\"Ира\",\"Олег\"]\nprint(names[1])",normalize:"code"},
{id:"p10",level:"hard",title:"Обновление",question:"Создай scores = [3,4,5], замени первый элемент на 5 и выведи список.",type:"text",answer:"scores=[3,4,5]\nscores[0]=5\nprint(scores)",normalize:"code"}]},
{id:"functions",icon:"🛠️",title:"Функции",short:"Создаём собственные команды.",description:"def, параметры и return.",
theory:["Функция — именованный блок кода, который можно вызывать несколько раз. Она помогает не повторять одинаковый код.","Функция создаётся через def. Параметры позволяют передавать ей данные.","return возвращает результат функции. Сначала полезно научиться писать маленькие функции: приветствие, сумму или вычисление площади."],
examples:[{code:"def hello():\n    print("Привет!")\n\nhello()",note:"Функция hello() вызывается после определения."},{code:"def add(a, b):\n    return a + b\n\nprint(add(2, 3))",note:"Функция принимает два числа и возвращает сумму."}],
tasks:[
{id:"f1",level:"easy",title:"Ключевое слово",question:"Каким словом создают функцию?",type:"choice",options:["def","func","function"],answer:"def"},
{id:"f2",level:"easy",title:"Возврат",question:"Как вернуть результат из функции?",type:"choice",options:["return","print","back"],answer:"return"},
{id:"f3",level:"easy",title:"Вызов",question:"Как вызвать функцию hello?",type:"choice",options:["hello()","call hello","run(hello)"],answer:"hello()"},
{id:"f4",level:"medium",title:"Простая функция",question:"Создай hello(), которая выводит \"Привет!\".",type:"text",answer:"def hello():\n    print(\"Привет!\")",normalize:"code"},
{id:"f5",level:"medium",title:"Вызови",question:"Создай hello() с print(\"Привет!\") и вызови её.",type:"text",answer:"def hello():\n    print(\"Привет!\")\nhello()",normalize:"code"},
{id:"f6",level:"medium",title:"Сумма",question:"Создай add(a,b), возвращающую a+b.",type:"text",answer:"def add(a,b):\n    return a+b",normalize:"code"},
{id:"f7",level:"medium",title:"Удвоение",question:"Создай double(x), возвращающую x*2.",type:"text",answer:"def double(x):\n    return x*2",normalize:"code"},
{id:"f8",level:"hard",title:"Площадь",question:"Создай area(a,b), возвращающую a*b.",type:"text",answer:"def area(a,b):\n    return a*b",normalize:"code"},
{id:"f9",level:"hard",title:"Приветствие",question:"Создай greet(name), которая выводит \"Привет, \" + name.",type:"text",answer:"def greet(name):\n    print(\"Привет, "+name)",normalize:"code"},
{id:"f10",level:"hard",title:"Калькулятор",question:"Создай add(a,b), верни сумму и выведи add(7,5).",type:"text",answer:"def add(a,b):\n    return a+b\nprint(add(7,5))",normalize:"code"}]},
{id:"debugging",icon:"🕵️",title:"Ошибки и отладка",short:"Учимся находить и исправлять ошибки.",description:"Синтаксис, имена переменных и логика.",
theory:["Ошибки — нормальная часть программирования. Важно читать сообщение об ошибке и искать причину, а не бояться ошибки.","SyntaxError часто означает проблему в записи кода. NameError появляется, когда программа не знает имя. Логическая ошибка возникает, когда код запускается, но результат неправильный.","Хороший способ отладки — проверить программу маленькими шагами, вывести значения переменных через print() и сравнить результат с ожидаемым."],
examples:[{code:"name = "Аня"\nprint(name)",note:"Имя переменной должно совпадать в обеих строках."},{code:"a = 2\nb = 3\nprint(a + b) # проверяем результат",note:"Комментарии после # помогают объяснять код и временно отключать часть строки."}],
tasks:[
{id:"d1",level:"easy",title:"SyntaxError",question:"Какая ошибка связана с неправильным синтаксисом?",type:"choice",options:["SyntaxError","NameError","ValueError"],answer:"SyntaxError"},
{id:"d2",level:"easy",title:"NameError",question:"Какая ошибка означает неизвестное имя?",type:"choice",options:["NameError","SyntaxError","TypeError"],answer:"NameError"},
{id:"d3",level:"easy",title:"Комментарий",question:"Как начинается комментарий в Python?",type:"choice",options:["#","//","<!--"],answer:"#"},
{id:"d4",level:"medium",title:"Исправь имя",question:"Исправь код, чтобы вывести name: name = \"Ира\".",type:"text",answer:"name=\"Ира\"\nprint(name)",normalize:"code"},
{id:"d5",level:"medium",title:"Исправь вычисление",question:"Исправь код, чтобы получить 12: a = 7, b = 5, print(a+b).",type:"text",answer:"a=7\nb=5\nprint(a+b)",normalize:"code"},
{id:"d6",level:"medium",title:"Проверка",question:"Создай x = 10 и выведи x для проверки значения.",type:"text",answer:"x=10\nprint(x)",normalize:"code"},
{id:"d7",level:"medium",title:"Комментарий",question:"Добавь комментарий # привет и затем выведи \"Привет\".",type:"text",answer:"# привет\nprint(\"Привет\")",normalize:"code"},
{id:"d8",level:"hard",title:"Лишний шаг",question:"Создай a = 5, b = 2 и выведи правильную сумму.",type:"text",answer:"a=5\nb=2\nprint(a+b)",normalize:"code"},
{id:"d9",level:"hard",title:"Проверяем цикл",question:"Создай i = 0 и выведи i, затем i = i + 1.",type:"text",answer:"i=0\nprint(i)\ni=i+1",normalize:"code"},
{id:"d10",level:"hard",title:"План отладки",question:"Создай result = 2 * 5 и выведи result — простой шаг проверки результата.",type:"text",answer:"result=2*5\nprint(result)",normalize:"code"}]},
{id:"project",icon:"🏁",title:"Мини-проекты",short:"Собираем знания в небольшие программы.",description:"Финальная практика: объединяем переменные, ввод, условия и циклы.",
theory:["Мини-проект — это задача, где несколько изученных инструментов работают вместе.","Перед кодом полезно составить план: какие данные нужны, что вычислить, какие условия проверить и что вывести.","Не обязательно писать всё сразу. Разбей проект на маленькие части и проверяй каждую часть отдельно. Так программа создаётся спокойнее и понятнее."],
examples:[{code:"name = input("Имя: ")\nscore = int(input("Баллы: "))\nif score >= 5:\n    print(name + ", молодец!")\nelse:\n    print(name + ", попробуй ещё!")",note:"Здесь вместе работают ввод, переменные, преобразование числа и условие."}],
tasks:[
{id:"m1",level:"easy",title:"Приветствие",question:"Получи name и выведи приветствие.",type:"text",answer:"name=input()\nprint(\"Привет, "+name)",normalize:"code"},
{id:"m2",level:"easy",title:"Счёт",question:"Создай score = 10 и выведи его.",type:"text",answer:"score=10\nprint(score)",normalize:"code"},
{id:"m3",level:"easy",title:"Проверка",question:"Выведи \"Ура\", если score >= 5.",type:"text",answer:"if score>=5:\n    print(\"Ура\")",normalize:"code"},
{id:"m4",level:"medium",title:"Калькулятор",question:"Создай a = 8, b = 2 и выведи сумму и произведение.",type:"text",answer:"a=8\nb=2\nprint(a+b)\nprint(a*b)",normalize:"code"},
{id:"m5",level:"medium",title:"Список дел",question:"Создай tasks = [\"учёба\", \"игра\", \"сон\"] и выведи первый элемент.",type:"text",answer:"tasks=[\"учёба\",\"игра\",\"сон\"]\nprint(tasks[0])",normalize:"code"},
{id:"m6",level:"medium",title:"Повторение",question:"Выведи \"Старт!\" 3 раза через for.",type:"text",answer:"for i in range(3):\n    print(\"Старт!\")",normalize:"code"},
{id:"m7",level:"medium",title:"Оценка",question:"Создай score = 4. Если score >= 5 — \"5+\", иначе — \"Нужно повторить\".",type:"text",answer:"score=4\nif score>=5:\n    print(\"5+\")\nelse:\n    print(\"Нужно повторить\")",normalize:"code"},
{id:"m8",level:"hard",title:"Сумматор",question:"Создай total = 0 и сложи числа 1–5 циклом.",type:"text",answer:"total=0\nfor i in range(1,6):\n    total=total+i",normalize:"code"},
{id:"m9",level:"hard",title:"Функция",question:"Создай square(x), возвращающую x*x, и выведи square(5).",type:"text",answer:"def square(x):\n    return x*x\nprint(square(5))",normalize:"code"},
{id:"m10",level:"hard",title:"Финальный проект",question:"Создай name = \"Аня\", score = 10 и выведи имя, затем \"Молодец\", если score >= 5.",type:"text",answer:"name=\"Аня\"\nscore=10\nprint(name)\nif score>=5:\n    print(\"Молодец\")",normalize:"code"}]}
];