window.LESSONS=[
{id:"variables",icon:"🟢",title:"Переменные",short:"Учимся хранить информацию в программе.",description:"Имя, значение и первое знакомство с присваиванием.",
theory:["Переменная — это имя, которое помогает программе запомнить значение.","В Python значение записывают с помощью знака =. Например: age = 12.","После этого Python может использовать имя age в других командах."],
examples:[{code:"name = \"Маша\"\nage = 12\nprint(name)\nprint(age)",note:"В переменных name и age хранятся имя и возраст."},{code:"score = 10\nscore = 15\nprint(score)",note:"Значение переменной можно изменить."}],
tasks:[
{id:"v1",level:"easy",title:"Найди переменную",question:"Какая переменная хранит возраст?",type:"choice",options:["name","age","print"],answer:"age"},
{id:"v2",level:"easy",title:"Имя переменной",question:"Как называется переменная в записи name = \"Аня\"?",type:"choice",options:["name","Аня","="],answer:"name"},
{id:"v3",level:"easy",title:"Значение",question:"Что хранится в переменной score после score = 10?",type:"choice",options:["score","10","print"],answer:"10"},
{id:"v4",level:"medium",title:"Создай age",question:"Напиши код: переменная age должна получить значение 12.",type:"text",answer:"age=12",normalize:"code"},
{id:"v5",level:"medium",title:"Создай имя",question:"Создай переменную name со значением \"Ира\".",type:"text",answer:"name=\"Ира\"",normalize:"code"},
{id:"v6",level:"medium",title:"Измени значение",question:"Создай score со значением 5, а затем измени его на 10. Напиши две строки.",type:"text",answer:"score=5\nscore=10",normalize:"code"},
{id:"v7",level:"medium",title:"Выведи переменную",question:"Создай переменную city со значением \"Алматы\" и выведи её через print.",type:"text",answer:"city=\"Алматы\"\nprint(city)",normalize:"code"},
{id:"v8",level:"hard",title:"Возраст через год",question:"Создай age = 12, затем создай next_age = 13.",type:"text",answer:"age=12\nnext_age=13",normalize:"code"},
{id:"v9",level:"hard",title:"Карточка ученика",question:"Создай name = \"Саша\", age = 11 и выведи name.",type:"text",answer:"name=\"Саша\"\nage=11\nprint(name)",normalize:"code"},
{id:"v10",level:"hard",title:"Мини-профиль",question:"Создай переменные name = \"Олег\", age = 14, city = \"Темиртау\" и выведи age.",type:"text",answer:"name=\"Олег\"\nage=14\ncity=\"Темиртау\"\nprint(age)",normalize:"code"}]},
{id:"types",icon:"🔵",title:"Типы данных",short:"Разбираемся, какие значения умеет хранить Python.",description:"Числа, строки и логические значения.",
theory:["В Python есть разные типы данных. Числа записываются без кавычек, строки — в кавычках.","int — целое число, float — дробное число, str — строка, bool — логическое значение True или False.","Функция type() помогает узнать тип значения."],
examples:[{code:"age = 12\nname = \"Маша\"\nheight = 1.55\nready = True",note:"Одна программа может хранить значения разных типов."},{code:"print(type(12))\nprint(type(\"Python\"))",note:"type() показывает тип значения."}],
tasks:[
{id:"t1",level:"easy",title:"Целое число",question:"Какой тип у значения 25?",type:"choice",options:["int","str","bool"],answer:"int"},
{id:"t2",level:"easy",title:"Строка",question:"Какой тип у значения \"Привет\"?",type:"choice",options:["int","str","float"],answer:"str"},
{id:"t3",level:"easy",title:"Логическое значение",question:"Что является логическим значением?",type:"choice",options:["True","12","\"да\""],answer:"True"},
{id:"t4",level:"medium",title:"Создай число",question:"Создай переменную age с целым числом 13.",type:"text",answer:"age=13",normalize:"code"},
{id:"t5",level:"medium",title:"Создай строку",question:"Создай переменную name со строкой \"Аня\".",type:"text",answer:"name=\"Аня\"",normalize:"code"},
{id:"t6",level:"medium",title:"Дробное число",question:"Создай переменную height со значением 1.6.",type:"text",answer:"height=1.6",normalize:"code"},
{id:"t7",level:"medium",title:"Проверка типа",question:"Напиши код, который выводит тип переменной age.",type:"text",answer:"print(type(age))",normalize:"code"},
{id:"t8",level:"hard",title:"Три типа",question:"Создай age = 12, name = \"Лена\", ready = True.",type:"text",answer:"age=12\nname=\"Лена\"\nready=True",normalize:"code"},
{id:"t9",level:"hard",title:"Определи типы",question:"Напиши три строки, выводящие типы 10, \"Python\" и 2.5.",type:"text",answer:"print(type(10))\nprint(type(\"Python\"))\nprint(type(2.5))",normalize:"code"},
{id:"t10",level:"hard",title:"Анкета",question:"Создай name = \"Иван\", age = 14, student = True и выведи тип age.",type:"text",answer:"name=\"Иван\"\nage=14\nstudent=True\nprint(type(age))",normalize:"code"}]},
{id:"linear",icon:"🟡",title:"Линейные алгоритмы",short:"Команды выполняются одна за другой.",description:"Ввод, вывод и арифметические операции.",
theory:["Линейный алгоритм выполняет команды по порядку — сверху вниз.","print() выводит информацию на экран, input() получает текст от пользователя.","В Python можно выполнять сложение, вычитание, умножение и деление."],
examples:[{code:"a = 5\nb = 3\nprint(a + b)",note:"Сначала создаются переменные, затем выполняется вычисление."},{code:"name = input(\"Имя: \")\nprint(\"Привет, \" + name)",note:"input() получает ответ пользователя."}],
tasks:[
{id:"l1",level:"easy",title:"Сложение",question:"Чему равно 7 + 5?",type:"choice",options:["10","12","13"],answer:"12"},
{id:"l2",level:"easy",title:"Умножение",question:"Чему равно 4 * 3?",type:"choice",options:["7","12","14"],answer:"12"},
{id:"l3",level:"easy",title:"Вывод",question:"Какая команда выводит текст на экран?",type:"choice",options:["print()","input()","type()"],answer:"print()"},
{id:"l4",level:"medium",title:"Сумма",question:"Создай a = 7, b = 5 и выведи их сумму.",type:"text",answer:"a=7\nb=5\nprint(a+b)",normalize:"code"},
{id:"l5",level:"medium",title:"Разность",question:"Создай a = 10, b = 4 и выведи a - b.",type:"text",answer:"a=10\nb=4\nprint(a-b)",normalize:"code"},
{id:"l6",level:"medium",title:"Произведение",question:"Создай x = 6, y = 3 и выведи x * y.",type:"text",answer:"x=6\ny=3\nprint(x*y)",normalize:"code"},
{id:"l7",level:"medium",title:"Приветствие",question:"Создай name = \"Миша\" и выведи Привет, Миша через print.",type:"text",answer:"name=\"Миша\"\nprint(\"Привет, \"+name)",normalize:"code"},
{id:"l8",level:"hard",title:"Периметр",question:"Создай a = 5, b = 3 и выведи периметр прямоугольника по формуле 2*(a+b).",type:"text",answer:"a=5\nb=3\nprint(2*(a+b))",normalize:"code"},
{id:"l9",level:"hard",title:"Два действия",question:"Создай x = 8, y = 2 и выведи сначала сумму, затем произведение.",type:"text",answer:"x=8\ny=2\nprint(x+y)\nprint(x*y)",normalize:"code"},
{id:"l10",level:"hard",title:"Мини-калькулятор",question:"Создай a = 20, b = 4 и выведи сумму, разность и частное.",type:"text",answer:"a=20\nb=4\nprint(a+b)\nprint(a-b)\nprint(a/b)",normalize:"code"}]},
{id:"conditions",icon:"🟠",title:"Условные алгоритмы",short:"Учимся принимать решения в программе.",description:"if, else, elif и логические условия.",
theory:["Условие позволяет программе выбрать действие.","if выполняет блок, когда условие истинно. else выполняется в другом случае.","Сравнения ==, !=, >, <, >= и <= помогают проверять значения."],
examples:[{code:"age = 12\nif age >= 12:\n    print(\"Можно!\")",note:"Если возраст не меньше 12, программа выводит сообщение."},{code:"score = 5\nif score >= 5:\n    print(\"Ура!\")\nelse:\n    print(\"Попробуй ещё\")",note:"if и else позволяют выбрать один из двух вариантов."}],
tasks:[
{id:"c1",level:"easy",title:"Сравнение",question:"Как записать проверку «x равно 10»?",type:"choice",options:["x = 10","x == 10","x != 10"],answer:"x == 10"},
{id:"c2",level:"easy",title:"Если",question:"Какое слово начинает условие в Python?",type:"choice",options:["if","for","def"],answer:"if"},
{id:"c3",level:"easy",title:"Иначе",question:"Какое слово задаёт действие, если условие ложно?",type:"choice",options:["else","print","input"],answer:"else"},
{id:"c4",level:"medium",title:"Проверка возраста",question:"Напиши if, который выводит \"Можно\" при age >= 12.",type:"text",answer:"if age>=12:\n    print(\"Можно\")",normalize:"code"},
{id:"c5",level:"medium",title:"Два варианта",question:"Если score >= 5, выведи \"Ура\", иначе выведи \"Ещё раз\".",type:"text",answer:"if score>=5:\n    print(\"Ура\")\nelse:\n    print(\"Ещё раз\")",normalize:"code"},
{id:"c6",level:"medium",title:"Равно",question:"Напиши условие, которое выводит \"Да\", если x == 10.",type:"text",answer:"if x==10:\n    print(\"Да\")",normalize:"code"},
{id:"c7",level:"medium",title:"Больше",question:"Выведи \"Большое\", если number > 100.",type:"text",answer:"if number>100:\n    print(\"Большое\")",normalize:"code"},
{id:"c8",level:"hard",title:"Чётность",question:"Выведи \"Чётное\", если number % 2 == 0, иначе \"Нечётное\".",type:"text",answer:"if number%2==0:\n    print(\"Чётное\")\nelse:\n    print(\"Нечётное\")",normalize:"code"},
{id:"c9",level:"hard",title:"Оценка",question:"Если score >= 5 выведи \"Молодец\", иначе \"Попробуй ещё\".",type:"text",answer:"if score>=5:\n    print(\"Молодец\")\nelse:\n    print(\"Попробуй ещё\")",normalize:"code"},
{id:"c10",level:"hard",title:"Три варианта",question:"Для age: если меньше 7 — \"Малыш\", если меньше 14 — \"Школьник\", иначе — \"Подросток\".",type:"text",answer:"if age<7:\n    print(\"Малыш\")\nelif age<14:\n    print(\"Школьник\")\nelse:\n    print(\"Подросток\")",normalize:"code"}]},
{id:"loops",icon:"🔴",title:"Циклические алгоритмы",short:"Повторяем действия с помощью циклов.",description:"for, while и range().",
theory:["Цикл повторяет одни и те же действия несколько раз.","for удобно использовать, когда известно количество повторений.","range() создаёт последовательность чисел, а while повторяет действия, пока условие истинно."],
examples:[{code:"for i in range(5):\n    print(i)",note:"Цикл выведет числа от 0 до 4."},{code:"count = 3\nwhile count > 0:\n    print(count)\n    count = count - 1",note:"while работает, пока условие count > 0 истинно."}],
tasks:[
{id:"o1",level:"easy",title:"Цикл for",question:"Какое слово используется для цикла по последовательности?",type:"choice",options:["for","if","while"],answer:"for"},
{id:"o2",level:"easy",title:"range",question:"Что выдаёт range(3) в цикле for?",type:"choice",options:["0, 1, 2","1, 2, 3","0, 1, 2, 3"],answer:"0, 1, 2"},
{id:"o3",level:"easy",title:"Условие цикла",question:"Какое слово используется для цикла, который работает пока условие истинно?",type:"choice",options:["while","for","else"],answer:"while"},
{id:"o4",level:"medium",title:"Пять раз",question:"Напиши цикл, который выводит слово \"Привет\" 5 раз.",type:"text",answer:"for i in range(5):\n    print(\"Привет\")",normalize:"code"},
{id:"o5",level:"medium",title:"Числа",question:"Напиши цикл, выводящий числа от 0 до 4.",type:"text",answer:"for i in range(5):\n    print(i)",normalize:"code"},
{id:"o6",level:"medium",title:"От 1 до 5",question:"Напиши цикл, выводящий числа от 1 до 5.",type:"text",answer:"for i in range(1,6):\n    print(i)",normalize:"code"},
{id:"o7",level:"medium",title:"Обратный отсчёт",question:"Создай count = 3 и с помощью while выводи count, уменьшая его на 1.",type:"text",answer:"count=3\nwhile count>0:\n    print(count)\n    count=count-1",normalize:"code"},
{id:"o8",level:"hard",title:"Квадраты",question:"С помощью for выведи квадраты чисел 1, 2 и 3.",type:"text",answer:"for i in range(1,4):\n    print(i*i)",normalize:"code"},
{id:"o9",level:"hard",title:"Сумма",question:"Создай total = 0 и в цикле от 1 до 5 прибавь i к total, затем выведи total.",type:"text",answer:"total=0\nfor i in range(1,6):\n    total=total+i\nprint(total)",normalize:"code"},
{id:"o10",level:"hard",title:"Финальный цикл",question:"Выведи 3 раза \"Python с нуля!\" с помощью цикла for.",type:"text",answer:"for i in range(3):\n    print(\"Python с нуля!\")",normalize:"code"}]}
];